//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NameIsNameCharacterGenerator.Services
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CharacterEntities : DbContext
    {
        public CharacterEntities()
            : base("name=CharacterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Character> Characters { get; set; }
        public virtual DbSet<Equipment> Equipments { get; set; }
        public virtual DbSet<Features_Traits> Features_Traits { get; set; }
        public virtual DbSet<Ideal> Ideals { get; set; }
        public virtual DbSet<Prof_Lang> Prof_Lang { get; set; }
    }
}
